# It's our root config
root: true

env:
  es6: true

ignorePatterns:
  - frontend/generated-api/**

overrides:
  # Gulp
  - files: gulpfile.js
    parserOptions:
      sourceType: module
    rules:
      strict: off
      camelcase: off

  # Embed TypeScript files
  - files: 'embed/**/*.ts'
    parser: '@typescript-eslint/parser'
    plugins:
      - '@typescript-eslint'
    extends:
      - 'eslint:recommended'
      - 'plugin:@typescript-eslint/eslint-recommended'
      - 'plugin:@typescript-eslint/recommended'
    rules:
      '@typescript-eslint/no-use-before-define':
        - warn
        - ignoreTypeReferences: true
      '@typescript-eslint/no-explicit-any': off
      '@typescript-eslint/no-non-null-assertion': off
      brace-style:
        - error
        - 1tbs
      camelcase: 2
      curly:
        - error
        - all
      eqeqeq:
        - error
        - smart
      indent:
        - error
        - 4
        - SwitchCase: 1
      new-cap: error
      no-bitwise: 2
      no-caller: error
      no-use-before-define: off # Replaced by @typescript-eslint/no-use-before-define
      object-shorthand: error
      prefer-template: error
      quote-props:
        - error
        - as-needed
      quotes:
        - error
        - single
      semi:
        - error
        - always
      strict:
        - error
        - function

  # Frontend TypeScript files
  - files: 'frontend/**/*.ts'
    parserOptions:
      project:
        - ./tsconfig.json
      createDefaultProgram: true
    extends:
      - 'eslint:recommended'
      - 'plugin:@typescript-eslint/recommended'
      - 'plugin:@angular-eslint/recommended'
      - 'plugin:@angular-eslint/template/process-inline-templates'
    rules:
      '@angular-eslint/component-selector':
        - error
        - type: element
          prefix: app
          style: kebab-case
      '@angular-eslint/directive-selector':
        - error
        - type: attribute
          prefix: app
          style: camelCase
      '@typescript-eslint/naming-convention':
        - error
        - selector: enumMember
          format:
            - camelCase
            - UPPER_CASE
      '@typescript-eslint/no-explicit-any': off
      '@typescript-eslint/no-non-null-assertion': off
      jsdoc/newline-after-description:
        - 'off'
      max-len:
        - 'off'
        - code: 140
      no-underscore-dangle:
        - 'off'

  # Frontend HTML files
  - files: 'frontend/**/*.html'
    extends:
      - 'plugin:@angular-eslint/template/recommended'
      - 'plugin:@angular-eslint/template/accessibility'
    rules:
      # This rule erroneously reports forms as needing a tabindex. Disable until
      # https://github.com/angular-eslint/angular-eslint/issues/1429 is resolved
      '@angular-eslint/template/interactive-supports-focus': off

  # Cypress Typescript
  - files: cypress/**/*.ts
    extends:
      - 'plugin:cypress/recommended'
    rules: {}
