# Almost empty secrets file for running e2e tests
postgres:
  host:     postgres
  port:     5432
  database: comentario
  username: postgres
  password: postgres

smtpServer:
  host:
  port:
  username:
  password:

  # Encryption used for sending mails. Possible values are "none", "ssl", "tls". Optional, if not provided, will pick
  # one based on the port number (25, 465, 587)
  #encryption: ssl

  # Whether to skip SSL certificate verification. Do NOT set to true in production!
  #insecure: false

idp:
  # Each of the providers below can be disabled by setting the `disable` field to `true`
  facebook:
    key:    facebook_key
    secret: facebook_secret
  github:
    key:    github_key
    secret: github_secret
  gitlab:
    key:    gitlab_key
    secret: gitlab_secret
  google:
    key:    google_key
    secret: google_secret
  linkedin:
    # LinkedIn auth doesn't work, see https://github.com/markbates/goth/issues/519
    disable: true
    key:      linkedin_key
    secret:   linkedin_secret
  twitter:
    key:    twitter_key
    secret: twitter_secret

extensions:
  # Each of the extensions below can be disabled by setting the `disable` field to `true`
  akismet:
    key:

  perspective:
    key:

  apiLayerSpamChecker:
    key:
