# Almost empty secrets file for running e2e tests
postgres:
  host:     postgres
  port:     5432
  database: comentario
  username: postgres
  password: postgres

smtpServer:
  host:
  port:
  username:
  password:

  # Encryption used for sending mails. Possible values are "none", "ssl", "tls". Optional, if not provided, will pick
  # one based on the port number (25, 465, 587)
  #encryption: ssl

  # Whether to skip SSL certificate verification. Do NOT set to true in production!
  #insecure: false

idp:
  facebook:
    key: blah
    secret: bluh
  github:
    key: blah
    secret: bluh
  gitlab:
    key: blah
    secret: bluh
  google:
    key: blah
    secret: bluh
  # LinkedIn auth doesn't work, see https://github.com/markbates/goth/issues/519
  #linkedin:
  #  key: blah
  #  secret: bluh
  twitter:
    key: blah
    secret: bluh

akismet:
  key:
