workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

stages:
  - build

variables:
  CI_TOOLS_VERSION: "v20"

build:
  stage: build
  image: registry.gitlab.com/comentario/comentario-ci-tools/builder:$CI_TOOLS_VERSION
  artifacts:
    when: always
    name: public
    paths:
      - public/
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm
  script:
    # Fetch the dependencies, specifying a cache location inside the build dir
    - npm ci --cache .npm

    # Build the site
    - npm run build
