#file: noinspection YAMLSchemaValidation
baseURL: https://docs.comentario.app/
languageCode: en
title: 'Comentario Documentation'

disableKinds:
- RSS
- sitemap

defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    weight: 1
  ru:
    weight: 2

module:
  hugoVersion:
    extended: true
    min: "v0.110"
  mounts:
    - source: node_modules
      target: assets/node_modules
    - source: assets
      target: assets
    - source: node_modules/@fortawesome/fontawesome-free/webfonts
      target: static/webfonts
    - source: static
      target: static

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: monokailight

sectionPagesMenu: sidebar

menu:
  # Will be lowercased in the template
  navbarExternal:
    - identifier: demo
      url: 'https://demo.comentario.app'
    - identifier: about
      url: '#about'
