baseURL: https://docs.comentario.app/
languageCode: en
title: 'Comentario: Comments Made Easy'

disableKinds:
- taxonomy
- term
- RSS
- sitemap

defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    weight: 1

module:
  hugoVersion:
    extended: true
    min: "v0.110"
  mounts:
    - source: node_modules
      target: assets/node_modules
    - source: assets
      target: assets
    - source: node_modules/@fortawesome/fontawesome-free/webfonts
      target: static/webfonts
    - source: static
      target: static

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: autumn

menu:
  navbar-external:
    - identifier: demo
      url: 'https://demo.comentario.app'
    - identifier: about
      url: '#about'
